#!/usr/bin/env bash

export CONTECO_LABEL="package.kafka_rest - ModEco"
export CONTECO_DESCRIPTION="Modeco kafka REST module package."

export CONTECO_TYPE="package"
export CONTECO_NAME="kafka_rest"
export CONTECO_TAG="6.0.0"


export CONTECO_BASE="image.wrapper"
export CONTECO_BUILD="modeco"
